name: CI

on:
  push:

jobs:
  examples:
    strategy:
      matrix:
        node: ["18"]
        os: [ubuntu]

    runs-on: ${{ matrix.os }}-latest
    name: examples
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: matter-labs/local-setup
          path: local-setup

      - name: Run server
        run: |
          cd local-setup
          ./start.sh &>../server.log &

      - uses: pnpm/action-setup@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Setup environment
        run: |
          pnpm install
          pnpm build

      - name: Wait until server is up
        run: |
          while ! curl -s -X POST -d '{"jsonrpc":"2.0","method":"net_version","id":1}' -H 'Content-Type: application/json' 0.0.0.0:3050; do sleep 1; done

      - name: Test zksolc example
        run: |
          cd examples/basic-example
          pnpm hardhat compile
          pnpm hardhat deploy-zksync

      - name: Test zksolc example with remote origin
        env:
          ZKSOLC_PATH: https://github.com/matter-labs/zksolc-bin/releases/download/v1.5.1/zksolc-linux-amd64-musl-v1.5.1
        run: |
          cd examples/download-with-compiler-origin
          pnpm hardhat compile
          pnpm hardhat deploy-zksync

      - name: Test deploy example
        run: |
          cd examples/deploy-example
          pnpm hardhat compile
          pnpm hardhat deploy-zksync

      - name: Test node example
        run: |
         cd examples/node-example
          pnpm hardhat compile
          pnpm hardhat test

      - name: Test noninline libraries example
        run: |
          cd examples/noninline-libraries-example
          pnpm hardhat compile
          pnpm hardhat deploy-zksync:libraries --private-key-or-index 0x7726827caac94a7f9e1b160f7ea819f172f7b6f9d2a97f992c38edeab82d4110
          pnpm hardhat compile
          pnpm hardhat deploy-zksync

      - name: Test zkvyper example
        run: |
          cd examples/vyper-example
          pnpm hardhat compile
          pnpm hardhat deploy-zksync

      - name: Test upgradable example
        run: |
          cd examples/upgradable-example
          pnpm hardhat compile
          pnpm hardhat run scripts/deploy-box-beacon.ts 
          pnpm hardhat run scripts/deploy-box-proxy.ts 
          pnpm hardhat run scripts/deploy-box-uups.ts 
          pnpm hardhat run scripts/upgrade-box-beacon.ts 
          pnpm hardhat run scripts/upgrade-box-uups.ts 
          pnpm hardhat run scripts/upgrade-box.ts
          pnpm hardhat run scripts/deploy-box-beacon-factory.ts 
          pnpm hardhat run scripts/deploy-box-proxy-factory.ts 
          pnpm hardhat run scripts/deploy-box-uups-factory.ts 
          pnpm hardhat run scripts/upgrade-box-uups-factory.ts 
          pnpm hardhat run scripts/upgrade-box-beacon-factory.ts 
          pnpm hardhat run scripts/upgrade-box-factory.ts 

      - name: Test upgradable example
        run: |
          cd examples/upgradable-example-l1
          pnpm hardhat compile
          pnpm hardhat run scripts/deploy-box-beacon.ts 
          pnpm hardhat run scripts/deploy-box-proxy.ts 
          pnpm hardhat run scripts/deploy-box-uups.ts 
          pnpm hardhat run scripts/upgrade-box-beacon.ts 
          pnpm hardhat run scripts/upgrade-box-uups.ts 
          pnpm hardhat run scripts/upgrade-box.ts 

      - name: Test zksync-ethers example
        run: |
          cd examples/zksync-ethers-example
          pnpm hardhat compile
          pnpm hardhat deploy-zksync

      - name: Show logs
        if: always()
        run: |
          cat server.log