name: Depricate packages/versions to npm
on:
  push:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm

      - name: Setup environment
        run: pnpm i && pnpm build
      - name: Depricate package version
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_NPM_MATTERLABS_AUTOMATION_TOKEN }}
        run: |
          npm deprecate @matterlabs/hardhat-zksync-toolbox "This plugin has been deprecated in favor of @matterlabs/hardhat-zksync plugin."
          npm deprecate @matterlabs/hardhat-zksync-chai-matchers "This plugin has been deprecated in favor of @nomicfoundation/hardhat-chai-matchers"